export const mockHome = {
  name: "Guruprasad Residence",
  tariff: 8.0,
  hubConnected: true,
  hubType: "Home Assistant",
  rooms: [
    { id: "r1", name: "Living Room", devices: ["d1", "d2"] },
    { id: "r2", name: "Master Bedroom", devices: ["d3"] },
    { id: "r3", name: "Kitchen", devices: ["d4", "d5"] },
    { id: "r4", name: "Guest Room", devices: [] },
  ],
  devices: [
    {
      id: "d1",
      name: "1.5T AC — Living Room",
      room: "Living Room",
      baseWatts: 1500,
      currentWatts: 1180,
      monthCost: 1850,
      todayCost: 62,
      powerFactor: 0.92,
      status: "on",
      identified: true,
      verified: true,
    },
    {
      id: "d2",
      name: "LED TV + Soundbar",
      room: "Living Room",
      baseWatts: 130,
      currentWatts: 96,
      monthCost: 210,
      todayCost: 7,
      powerFactor: 0.9,
      status: "on",
      identified: true,
      verified: true,
    },
    {
      id: "d3",
      name: "Cooler",
      room: "Master Bedroom",
      baseWatts: 220,
      currentWatts: 148,
      monthCost: 95,
      todayCost: 3,
      powerFactor: 0.95,
      status: "off",
      identified: true,
      verified: false,
    },
    {
      id: "d4",
      name: "Refrigerator",
      room: "Kitchen",
      baseWatts: 320,
      currentWatts: 260,
      monthCost: 640,
      todayCost: 21,
      powerFactor: 0.85,
      status: "on",
      identified: true,
      verified: true,
    },
    {
      id: "d5",
      name: "Washing Machine",
      room: "Kitchen",
      baseWatts: 500,
      currentWatts: 0,
      monthCost: 320,
      todayCost: 0,
      powerFactor: 0.88,
      status: "paused",
      identified: true,
      verified: true,
    },
  ],
};

export const proTariffInfo = {
  freeTariff: 8.0,
  proTariff: 7.2,
  proNote: "PRO tariff savings (₹0.80/unit) applied in blue mode.",
};